### ISSUE TITLE
VMS data submission checklist-futurible issues

### ISSUE THREAD

**Issue by LaraSalvany** [ices-tools-dev/AdviceProcesses#3]
- [ ] Carlos to upload in database for Colin
- [ ] Colin to do QC report
- [ ] Christian to redmark QC report
- [ ] Niels to double check QC report
- [ ] Inform countries about VMS data status
- [ ] Resubmission process
- [ ] Point of no return
- [ ] Aggregated data products
- [ ] Quality check aggregated data products
- [ ] VMS data products
- [ ] Technical review of VMS data products
- [ ] ADGVME
- [ ] Minor changes
- [ ] Release of the advice
